### ISSUE TITLE
Discussion: Move Jira functionality to a separate project?

### ISSUE THREAD

**Issue by bavovanachte** [melexis/sphinx-traceability-extension#177]
Would it make sense to move the Jira functionality out of this project? As this is a public project (not only contained to Melexis), I feel that adding the Jira integration could open the door to also adding support for a bunch of other tools (there's a gazillion bug-tracking tools out there). 

Don't get me wrong, I think integrations with other tooling are interesting and should be encouraged. I'm just wondering if we shouldn't adjust the plugin architecture to keep things maintainable with a relatively small team. A possibility would be to set up a plugin/extension system of our own. Could be as simple as cleaning up the json output (documentation) or adding our own plugin hooks.

I think that besides reducing complexity/maintenance on the traceability plugin itself, it could also lower the bar for community contributions (people can quickly set up their own plugin without needing to comply to the same coding standards). 
Downside would be that we have to be more careful with our interface to the extension system to ensure backwards compatibility whenever we make changes.

**Comment by Letme** [comment]
I would say it is a good idea, but the problem I see is that currently this is tightly integrated within the plugin. Maybe @JasperCraeghs could find some time to do this?

Also plugin/extension system from Sphinx I think it is what we should use. Same as how Coverity plugin is dependent on mlx.traceability, same should we make this `jira-traceability` feature somehow working without tight integration to traceability internals. No idea if that is possible at all.

**Comment by JasperCraeghs** [comment]
I've been thinking about this some more and I think that it makes sense to split this feature off into a separate Sphinx plugin similarly to `mlx.coverity`. 

I believe it is possible to move the Jira interaction feature to a separate Sphinx extension, to be run by Sphinx after it has run mlx.traceability. Because at that point `mlx.jira-interaction` has access to `app.builder.env.traceability_collection` and, therefore, the handy internals of `mlx.traceability`. Porting _mlx/jira_interaction.py_ will be really easy this way. 

Alternatively _- but not preferred by me -_ the jira interaction feature could be moved to a simple Python script instead of a Sphinx extension/plugin by parsing the JSON-output of `mlx.traceability`. This requires a lot of changes to _mlx/jira_interaction.py_ because the internals of `mlx.traceability` are not really accessible.

**Comment by Letme** [comment]
I would indeed got the way of additional Sphinx extension and forget about parsing json output as JIRA plugin is now set as part of the Sphinx documentation build and I think it should stay that way.

**Comment by JasperCraeghs** [comment]
How do we call this new plugin? Here are some suggestions:

- mlx.jira-interaction
- mlx.jira-traceability
- mlx.jira-ticket-creator

What do you suggest?

**Comment by bavovanachte** [comment]
Discussed offline: mlx.jira-traceability seems like a good option: it indicates that there's jira interaction, but that it's not a generic jira plugin but linked to the traceability plugin.
