### ISSUE TITLE
Add option to filter on targets' attributes in item-2d-matrix

### ISSUE THREAD

**Issue by YvenMauroo** [melexis/sphinx-traceability-extension#197]
**Use case:**

The 2d item matrix is ideal to visualize which tests should run at which conditions. The condition items are in the order of 3 to 8 different items while the test items can be a lot (like 100). Such a list of tests can vary between products so adding an attribute to a test item which identifies the product it should be used would give the ability to filter the 2d matrix. As the attribute filter is anly applicable to the source and not the target, source needs to be test items while target has to be condition items. This will generate a very wide table that is not suitable to read. A long table would fix this issue by using a transpose option.

**Comment by JasperCraeghs** [comment]
While resolving issue #83, I couldn't find a use case for a transpose option for the item-2d-matrix directive. You've found a use case for it. However, I don't think that a transpose flag is the most elegant or user-friendly solution here. 

Instead, I suggest the addition of a different flag, `:filtertarget:`, which changes the attribute filtering to apply to target items instead of source items. The implementation is easier and it's more user-friendly because all other options, e.g. source, target, and type, can remain the same.
