### ISSUE TITLE
Conditional items

### ISSUE THREAD

**Issue by basejumpa** [melexis/sphinx-traceability-extension#355]
Background/Movivation:

I'd like to use the extension mlx.traceability for the specification ecosystem of a **software product line**. The specifications describe every possible product which may be derived from the product line. Therefore there are placeholders which are to be replaced and parts of the content which may not be present in the generated output. A product specification is derived from the product line specification using the product's configuration. 

In order to support this scenario I'd like to contribute the following new feature:

**Conditional items**

There shall be a built-in, optional attribute `ifconfig`. Only if the value of the attribute evaluates to true the item shall be present in the document. The expression is evaluated in the namespace of the project’s configuration.

Example:

```
.. item:: DESIGN_0001
    :ifconfig: feature_A_enabled

    This is the content of the item. Bla bla ...
```

It is similar to the extension [sphinx.ext.ifconfig](https://www.sphinx-doc.org/en/master/usage/extensions/ifconfig.html).

Because of the **relationships** between items there are more thoughts to make about it. Before we discuss them and make the appropriate design decisions I'd like to know if you guys would support such enhancement in general.

I appreciate your feedback!

**Comment by JasperCraeghs** [comment]
We use the `only`-directive, modified by the [eager_only](https://github.com/pfalcon/sphinx_selective_exclude#eager_only) extension, to conditionally define any directive. It seems to be similar to the `ifconfig`-directive you linked to, but I have never used it. Can the `ifconfig`-directive be used to conditionally define items? 

Using a dedicated directive makes sense to me because:
- It works for all types of content/directives.
- The condition can be applied to multiple directives at once.
- The content must be indented, so it's easy to spot what is defined conditionally.

**Comment by basejumpa** [comment]
@JasperCraeghs Thx for your input.

The `ifconfig` directive has the same weakness as the built-in `only` directive. Based on your input I think it makes more sense to develop a `eager_ifconfig` directive rather than making mlx.traceability more complex by the `:ifconfig:` attribute.

From my side this issue can be closed.

Thx again!
