### ISSUE TITLE
Add possibility to add attributes from RST documents

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/sphinx-traceability-extension#76]
Currently attributes can only be added in conf.py. It would be better if we can also add item-attributes from RST documents. A new directive `item-attribute` is needed that defines an attribute:

- unique id
- translated string name
- regex for matching values against
- description (as requested in #75 )

**Comment by Letme** [comment]
I like current idea because if you make a typo, it gives you an error. Now you will have to stroll throught all the documents to find this, so while it allows more flexibility it also produces less organization and doc will become mixture of definitions and configurations. 

In a sense it sounds like this is done because for some reason you cannot chabhe conf.py?

**Comment by SteinHeselmans** [comment]
close: import from conf.py seems sufficient
